import type { Metadata } from 'next';

import '@/styles/main.css';
import { Root } from '@/layouts/Root';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <Root>{children}</Root>;
}
